Feature/split function arguement
marleenlukei/DecisionTreeAndRandomForest.jl pull request #10
Opened 2024-06-16 12:23 UTC by arkadeep16121993

Added the split function in ClassificationTree and tweaked the split function codes accordingly

2024-06-16 12:39 UTC, arkadeep16121993 commented
The test files needs to be changed to pass the checks

2024-06-19 13:01 UTC, cedric-len requested changes
Please add the docstrings you removed and delete the `SplitCriterion.jl` file

2024-06-19 13:01 UTC, cedric-len commented on src/ClassificationTree.jl
> -Represents a Leaf in the ClassificationTree structure.
These docstrings should not be deleted!

2024-06-19 13:01 UTC, cedric-len commented on src/ClassificationTree.jl
> -Represents a Node in the ClassificationTree structure.
see above

2024-06-19 13:01 UTC, cedric-len commented on src/ClassificationTree.jl
> -`max_depth` controls the maximum depth of the tree. If -1, the depth is not limited.
see above

2024-06-19 13:01 UTC, cedric-len commented on src/ClassificationTree.jl
> -    build_tree(data, labels, max_depth, min_samples_split, depth)
see above

2024-06-19 13:01 UTC, cedric-len commented on src/ClassificationTree.jl
> -    fit(tree::ClassificationTree)
see above

2024-06-19 13:01 UTC, cedric-len commented on src/ClassificationTree.jl
> -    print_tree(tree:ClassificationTree)
see above

2024-06-19 13:01 UTC, cedric-len commented on src/SplitCriterion.jl
> +module SplitCriterion
remove this entirely, since it is not used

2024-06-19 13:01 UTC, cedric-len commented on test/test_classificationtree.jl
> +    # Using Information Gain criterion
remove this comment

2024-06-19 16:47 UTC, closed without merging